global:
  domain: nagarsewa-jenkins.uk.gov.in ## Add your Domain Name Eg: site.mydomain.com
  setup: fullsetup
  
cluster-configs:
  namespaces:
    create: true
    values: [ jenkins, monitoring ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

# jenkins:
#   persistence:
#     enabled: true
#     aws:
#       - volumeId: "vol-054ce663f9040ea17" # Add volume id for jenkins-home
#         zone: ap-south-1b # Add respective availability_zones 

  oauth:
    enabled: true
    acl:
      admin:
        - eNagarsewaU*UKD-service-devops
      user:
        - eNagarsewaU*ukd-dev
       

  jobBuilder:
    repos: >-
      'git@github.com:eNagarsewaU/DIGIT-UKD.git','git@github.com:eNagarsewaU/ukd-rainmaker-customization.git'

  deploymentJobs:  
    - name: ukd-uat
      acl: [eNagarsewaU*ukd-uat]   
    - name: ukd-prod
      acl: [eNagarsewaU*ukd-prod] 
    
       
  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    javaOpts: "-Xms2560M -Xmx2560M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: egovio/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  clusterIssuer:
    stage:
      acme:
        email: "githuboauth@egovernments.org"     # Add mail id

# cluster-autoscaler:
#   namespace: jenkins
#   cloudProvider: aws  
#   awsRegion: ap-south-1
#   autoDiscovery:
#     clusterName: jenkins-cluster # Add cluster name
#     tags:
#     - kubernetes.io/cluster/jenkins-cluster # Add cluster name
