{{- if .Values.controller.addHeaders -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "nginx-ingress.fullname" . }}-custom-add-headers
  namespace: {{ .Values.namespace }}
data: {{ toYaml .Values.controller.addHeaders | nindent 2 }}
{{- end }}
