{{- if .Values.controller.admissionWebhooks.enabled }}
{{- if .Values.controller.admissionWebhooks.networkPolicyEnabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-webhooks-allow
  namespace: {{ .Values.namespace }}
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx-ingress.name" . }}
  policyTypes:
    - Ingress

{{- end }}
{{- end }}
